name: Addons
version: '${project.version}'
depend: [PlaceholderAPI, LuckPerms, eco]
main: me.dawey.addons.Addons
api-version: '1.20'
commands:
  addonsinvsee:
    description: Invsee command
  addons:
    description: Addons command
  stash:
    description: Stash command
    aliases: [ stashes ]

permissions:
  addons.stash.admin:
    description: Admin permission for stash command
    default: op
  addons.bypass.crafting:
    description: Bypass crafting permission
    default: op