name: Addons
version: '${project.version}'
depend: [PlaceholderAPI, LuckPerms]
main: me.dawey.addons.Addons
api-version: '1.20'
commands:
  addonsinvsee:
    description: Invsee command
permissions:
  addons.stash.admin:
    description: Admin permission for stash command
    default: op
  addons.bypass.crafting:
    description: Bypass crafting permission
    default: op