### Addons Discord Bot Config ###
webhook:
  url: ""
  system-name: "System"
  system-avatar: ""

bot:
  token: ""
  guild-id: ""
  descriptions:
    - "play.xyz.hu"

channels:
  server-channel: ""

roles:
  default: ""
  magician: ""
  wizard: ""
  mage: ""